// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn94WOTIm8w3bGjdpeCmiZ1gmIQdbFVxk',
    appId: '1:711810787659:web:80b3d4ff8e62a7b53720ce',
    messagingSenderId: '711810787659',
    projectId: 'hmart-fc31e',
    authDomain: 'hmart-fc31e.firebaseapp.com',
    storageBucket: 'hmart-fc31e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf40mgaAaKTPtEvLkLxJwDei23eQ2ISCg',
    appId: '1:711810787659:android:34d547e6f9b888523720ce',
    messagingSenderId: '711810787659',
    projectId: 'hmart-fc31e',
    storageBucket: 'hmart-fc31e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyyLEmTccxOTl2KwEQDO51ihp1PcQB-f0',
    appId: '1:711810787659:ios:5815856b8b8a5dad3720ce',
    messagingSenderId: '711810787659',
    projectId: 'hmart-fc31e',
    storageBucket: 'hmart-fc31e.appspot.com',
    iosBundleId: 'com.example.hMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyyLEmTccxOTl2KwEQDO51ihp1PcQB-f0',
    appId: '1:711810787659:ios:a34827e3ef9c831c3720ce',
    messagingSenderId: '711810787659',
    projectId: 'hmart-fc31e',
    storageBucket: 'hmart-fc31e.appspot.com',
    iosBundleId: 'com.example.hMart.RunnerTests',
  );
}
